version: '3'
services:
    dc-node1:
        build:
            context: .
        image: mdbg
        privileged: true
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
            BOOTSTRAP: 1
        volumes:
            - ../init:/tmp/init
        hostname: dcg1
        container_name: dcg1
        networks:
            static-network:
                ipv4_address: 172.20.0.2
        ports:
            - "4002:3306"
    dc-node2:
        build:
            context: .
        image: mdbg
        privileged: true
        depends_on:
            - dc-node1
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
            BOOTSTRAP: 0
        volumes:
            - ../init:/tmp/init
        hostname: dcg2
        container_name: dcg2
        networks:
            static-network:
                ipv4_address: 172.20.0.3
        ports:
            - "4003:3306"

    dc-node3:
        build:
            context: .
        image: mdbg
        privileged: true
        depends_on:
            - dc-node1
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
            BOOTSTRAP: 0
        volumes:
            - ../init:/tmp/init
        hostname: dcg3
        container_name: dcg3
        networks:
            static-network:
                ipv4_address: 172.20.0.4
        ports:
            - "4004:3306"
    dr-node1:
        build:
            context: .
        image: mdbg
        privileged: true
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
            BOOTSTRAP: 1
        volumes:
            - ../init:/tmp/init
        hostname: drg1
        container_name: drg1
        networks:
            static-network:
                ipv4_address: 172.20.0.6
        ports:
            - "4006:3306"
    dr-node2:
        build:
            context: .
        image: mdbg
        privileged: true
        depends_on:
            - dr-node1
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
            BOOTSTRAP: 0
        volumes:
            - ../init:/tmp/init
        hostname: drg2
        container_name: drg2
        networks:
            static-network:
                ipv4_address: 172.20.0.7
        ports:
            - "4007:3306"
    dr-node3:
        build:
            context: .
        image: mdbg
        privileged: true
        depends_on:
            - dr-node1
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'Y'
            BOOTSTRAP: 0
        volumes:
            - ../init:/tmp/init
        hostname: drg3
        container_name: drg3
        networks:
            static-network:
                ipv4_address: 172.20.0.8
        ports:
            - "4008:3306"
networks:
    static-network:
        name: static-network
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  ip_range: 172.20.5.0/24
                  gateway: 172.20.5.254
